    <h1>редактирование пользователя</h1>
    <form action="/users/<?= htmlspecialchars($user['id']) ?>" method="post">
        <input type="hidden" name="_METHOD" value="PATCH">
        <div>
            <label for="nickname">Nickname:</label>
            <input type="text" name="user[nickname]" id="nickname" value="<?= htmlspecialchars($user['nickname']) ?>">
            <?php if (isset($errors['nickname'])): ?>
                <div class="error"><?= $errors['nickname'] ?></div>
            <?php endif ?>
        </div>
        <div>
            <label for="email">Email:</label>
            <input type="text" name="user[email]" id="email" value="<?= htmlspecialchars($user['email']) ?>">
            <?php if (isset($errors['email'])): ?>
                <div class="error"><?= $errors['email'] ?></div>
            <?php endif ?>
        </div>
        <button type="submit">Update User</button>
    </form>
    <a href="/users">Back to Users</a>