<a href="/users">Все Пользователи</a>

<h1>Список пользователей</h1>

<form action="/users" method="get">
    <label for="term">Поиск по имени:</label>
    <input type="text" name="term" id="term" value="<?= $term ?>">
    <button type="submit">Поиск</button>
</form>

<?php if (!empty($users)): ?>
    <ul>
        <?php foreach ($users as $user): ?>
            <li><?= htmlspecialchars($user['firstName']) ?></li>
        <?php endforeach ?>
    </ul>
<?php else: ?>
    <p>Пользователи не найдены.</p>
<?php endif; ?>
