<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Живой Поиск</title>
</head>
<body>
    <a href="/users">Все Пользователи</a>
    <br>
    <br>
    <input type="text" id="searchTerm" placeholder="Поиск по имени">
    <ul id="userList">
        <?php foreach ($users as $user): ?>
            <li><?= htmlspecialchars($user['firstName']) ?></li>
        <?php endforeach ?>
    </ul>

    <script>
        document.getElementById('searchTerm').addEventListener('input', function(e) {
            var term = e.target.value;
            fetch('/api/users?term=' + term)
                .then(response => response.json())
                .then(data => {
                    var userList = document.getElementById('userList');
                    userList.innerHTML = '';
                    data.users.forEach(user => {
                        var li = document.createElement('li');
                        li.textContent = user.firstName;
                        userList.appendChild(li);
                    });
                });
        });
    </script>
</body>
</html> -->






