<h2>ID: <?= htmlspecialchars($id) ?></h2>
<h2>Nickname: <?= htmlspecialchars($nickname) ?></h2>



<!-- 
<a href="/users">Пользователи</a>

<h1>Информация о пользователе</h1>
<p>Имя: <?= $user['firstName'] ?></p>
<p>Фамилия: <?= $user['lastName'] ?></p>
<p>Email: <?= $user['email'] ?></p>
<p>Город: <?= $user['city'] ?></p>
<?php if (isset($user['temperature'])): ?>
    <p>Температура в городе: <?= $user['temperature'] ?>°C</p>
<?php endif; ?> -->
