<!-- <h2>ID: <?= htmlspecialchars($id) ?></h2>
<h2>Nickname: <?= htmlspecialchars($nickname) ?></h2>







<a href="/users">Пользователи</a>

<h1>Информация о пользователе</h1>
<p>Имя: <?= $user['firstName'] ?></p>
<p>Фамилия: <?= $user['lastName'] ?></p>
<p>Email: <?= $user['email'] ?></p>
<p>Город: <?= $user['city'] ?></p>
<?php if (isset($user['temperature'])): ?>
    <p>Температура в городе: <?= $user['temperature'] ?>°C</p>
<?php endif; ?> -->






<!-- <h1>Добро пожаловать!</h1>

<p><a href="/users">Посмотреть список пользователей</a></p>
<h1>Список пользователей</h1>
<ul>
    <?php foreach ($users as $user): ?>
        <li><a href="/users/<?= $user['id'] ?>"><?= $user['id'] ?>. <?= $user['firstName'] ?> <?= $user['lastName'] ?></a></li>
    <?php endforeach ?>
</ul> -->






<h1>User List</h1>
<ul>
    <?php foreach ($users as $user): ?>
    <li>
        Nickname: <?= htmlspecialchars($user['nickname']) ?><br>
        Email: <?= htmlspecialchars($user['email']) ?><br>
    </li>
    <br> 
    <?php endforeach; ?>
</ul>
<a href="<?= $createUrl ?>">Create New User</a>